kragaht/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from kragaht import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('category/<slug:category_slug>/', views.category_posts, name='category_posts'),  # Filter posts by a category
    path('post/<slug:post_slug>/', views.post_detail, name='post_detail'),
    path('post/<int:post_id>/like/', views.toggle_like, name='toggle_like'),
    path('create/', views.post_create, name='post_create'),
    path('edit/<int:pk>/', views.post_edit, name='post_edit'),
    path('delete/<int:pk>/', views.post_delete, name='post_delete'),
    path('register/', views.user_register, name='user_register'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('my-posts/', views.my_posts, name='my_posts'),
    path('liked-posts/', views.liked_posts, name='liked_posts'),
]

posts/models.py
from ckeditor.fields import RichTextField
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='URL')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('posts:category_posts', kwargs={'category_slug': self.slug})


class Post(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='URL')
    content = RichTextField()  # CKEditor
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, blank=True, null=True)
    photo = models.ImageField(upload_to='post_photos/', blank=True, null=True)
    time_create = models.DateTimeField(auto_now=True)
    time_update = models.DateTimeField(auto_now=True)
    likes = models.ManyToManyField(User, related_name='liked_posts', blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('posts:post_detail', kwargs={'post_slug': self.slug})

    def can_edit_or_delete(self, user):
        return user == self.author or user.is_staff

    def get_like_count(self):
        return self.likes.count()

    def user_liked(self, user):
        return self.likes.filter(id=user.id).exists()

posts/forms.py
from ckeditor.widgets import CKEditorWidget
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Post


class PostForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorWidget())  # CKEditor

    class Meta:
        model = Post
        fields = ['title', 'content', 'photo', 'category']


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your username'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Enter your password'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirm your password'}),
        }

posts/views.py
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post, Category
from .forms import PostForm


def category_posts(request, category_slug):  # Display posts that belong to a specific category.

    category = get_object_or_404(Category, slug=category_slug)
    posts = Post.objects.filter(category_id=category.pk)
    categories = Category.objects.all()
    return render(request, 'posts/category_posts.html', {'category': category, 'categories': categories, 'posts': posts})


def my_posts(request):
    categories = Category.objects.all()
    if not request.user.is_authenticated:
        return redirect('/login')
    else:
        user_posts = Post.objects.filter(author=request.user)
        return render(request, 'posts/my_posts.html', {'posts': user_posts, 'categories': categories})


def post_list(request):
    query = request.GET.get('q')  # Search query
    sort_by = request.GET.get('sort', 'time_create')

    if query:
        posts = Post.objects.filter(title__icontains=query)
    else:
        posts = Post.objects.all()
    # sorting
    if sort_by == 'name':
        posts = posts.order_by('title')
    elif sort_by == 'likes':
        posts = posts.annotate(like_count=Count('likes')).order_by('-like_count')
    elif sort_by == 'time_create':
        posts = posts.order_by('-time_create')

    for post in posts:
        post.user_liked = request.user.is_authenticated and post.likes.filter(id=request.user.id).exists()

    categories = Category.objects.all()

    return render(request, 'posts/post_list.html', {
        'posts': posts, 'categories': categories, 'query': query, 'sort_by': sort_by,
    })


def post_detail(request, post_slug):
    post = get_object_or_404(Post, slug=post_slug)
    similar_posts = Post.objects.exclude(id=post.id)[:5]
    categories = Category.objects.all()
    return render(request, 'posts/post_detail.html', {
        'post': post,
        'similar_posts': similar_posts,
        'categories': categories,
    })


def liked_posts(request):
    categories = Category.objects.all()
    if not request.user.is_authenticated:
        return redirect('login')

    liked_posts = Post.objects.filter(likes=request.user)
    return render(request, 'posts/liked_posts.html', {'posts': liked_posts, 'categories': categories})


def toggle_like(request, post_id):
    if request.method == 'POST' and request.user.is_authenticated:
        post = get_object_or_404(Post, id=post_id)
        if post.likes.filter(id=request.user.id).exists():
            post.likes.remove(request.user)
            liked = False
        else:
            post.likes.add(request.user)
            liked = True

        return JsonResponse({'liked': liked, 'like_count': post.get_like_count()})
    return JsonResponse({'error': 'Invalid request'}, status=400)


@login_required
def post_create(request):
    categories = Category.objects.all()
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:post_list')
    else:
        form = PostForm()
    return render(request, 'posts/post_form.html', {'form': form, 'form_title': 'Create Post', 'categories': categories})


@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.user != post.author and not request.user.is_staff:
        return redirect('posts:post_list')
    categories = Category.objects.all()
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect('posts:post_detail', post_slug=post.slug)
    else:
        form = PostForm(instance=post)
    return render(request, 'posts/post_form.html', {'form': form, 'categories': categories})


@login_required
def post_delete(request, pk):

    post = get_object_or_404(Post, pk=pk)
    if request.user != post.author and not request.user.is_staff:
        return redirect('posts:post_list')
    if request.method == 'POST':
        post.delete()
        return redirect('posts:post_list')
    return render(request, 'posts/post_confirm_delete.html', {'post': post})


def user_register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Registration successful! You can now log in.')
            return redirect('/')
    else:
        form = UserCreationForm()

    return render(request, 'posts/register.html', {'form': form})


def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('posts:post_list')
    else:
        form = AuthenticationForm()
    return render(request, 'posts/login.html', {'form': form})


def user_logout(request):
    logout(request)
    return redirect('posts:post_list')

posts/templates/posts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kragaht</title>
    <link rel="stylesheet" href="{% static 'posts/css/css_styles.css' %}">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'posts/img/griff.png' %}"/>
</head>
<body>
    <header>
        <div class="header-left">
            <div class="logo"><img src="{% static 'posts/img/griff.png' %}"></img></div>
            <h1>Kragaht</h1>
       <div class="header-center">
    <form method="get" action="{% url 'posts:post_list' %}">
        <input
            type="text"
            name="q"
            class="search-box"
            placeholder="Search posts..."
            value="{{ query|default:'' }}"
        >
        <button type="submit" class="search-button">Search</button>
    </form>
</div>

        <div class="header-right">
            <button class="sign-in"><a href="{% url 'posts:user_register' %}"> Sign In</a></button>
            {% if user.is_authenticated %}
              <button class="sign-in"><a href="{% url 'posts:user_logout' %}"> Logout </a></button>
            {% else %}
            <button class="sign-in"><a href="{% url 'posts:user_login' %}"> Login</a></button>
            {% endif %}
        </div>
    </header>
    <div class="container">
        <aside class="sidebar">
            <ul class="sdb">
                <li><a href="{% url 'posts:post_list' %}">Home</a></li>
                <li class="category-item">
                    <a href="#">Category</a>
                    <div class="red-square"></div>
                    <ul class="categories-dropdown" id="dropdownMenu">
                        {% for category in categories %}
                    <li><a href="{{ category.get_absolute_url }}">{{ category.name }}</a></li>
                {% endfor %}
                    </ul>
                </li>
                <li><a href="{% url 'posts:liked_posts' %}">Liked Posts</a></li>
                <li><a href="{% url 'posts:my_posts' %}">My Posts</a></li>
                {% if user.is_authenticated %}
                <li> <a href="{% url 'posts:post_create' %}" class="category-item">Add New Post</a>
    {% endif %}
            </ul>
        </aside>
        <main class="content">
            {% block content %}
            {% endblock %}
        </main>
    </div>
    <script> <!-- dropdown of categories -->
        document.addEventListener('DOMContentLoaded', function () {
            const redSquare = document.querySelector('.red-square');
            const dropdownMenu = document.getElementById('dropdownMenu');

            redSquare.addEventListener('click', function () {
                dropdownMenu.classList.toggle('visible');
            });
        });
    </script>
</body>
</html>

posts/templates/posts/category_posts.html
{% extends 'posts/base.html' %}

{% block title %}{{ category.name }} - Kragaht{% endblock %}

{% block content %}
<div class="post-container">
    {% for post in posts %}
        <div class="post-card">
            <div class="post-image">
                {% if post.photo %}
                    <img src="{{ post.photo.url }}" alt="{{ post.title }}">
                {% else %}
                    <div class="placeholder-image"></div>
                {% endif %}
                <div class="read-post-container">
                    <a href="{% url 'posts:post_detail' post.slug %}" class="read-post">Read Post</a>
                    <div class="post-interactions">
    <button class="like-button" data-id="{{ post.id }}">
        {% if post.user_liked %}
            &#9650;
        {% else %}
           &#9650;
        {% endif %}
    </button>
    <span id="like-count-{{ post.id }}">{{ post.get_like_count }}</span>: Likes
</div>
                </div>
            </div>
            <div class="post-cont-content">
                <div class="post-header">
                    <div class="post-title">{{ post.title }}</div>
                    <div class="post-meta">
                        <span>Author: {{ post.author.username }}</span>
                        <span>Date: {{ post.time_update|date:"d-m-Y H:i" }}</span>
                    </div>
                </div>
                <div class="post-description">
                    {{ post.content|truncatewords:20 }}
                </div>
            </div>
        </div>
    {% endfor %}
    {% if not posts %}
        <p>No posts in this category yet.</p>
    {% endif %}

</div>

<!-- JavaScript AJAX Like System -->
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const likeButtons = document.querySelectorAll('.like-button');
        likeButtons.forEach(button => {
            button.addEventListener('click', function () {
                const postId = this.getAttribute('data-id');
                const likeCountSpan = document.getElementById(`like-count-${postId}`);

                fetch(`/post/${postId}/like/`, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': '{{ csrf_token }}',
                    },
                })
                .then(response => {
                    if (!response.ok) {
                        throw new Error('Network response was not ok');
                    }
                    return response.json();
                })
                .then(data => {
                    if (data.liked !== undefined) {
                        this.innerHTML = data.liked ? '&#9650;' : '&#9650;';
                        likeCountSpan.textContent = data.like_count;
                    }
                })
                .catch(error => console.error('Error:', error));
            });
        });
    });
</script>
{% endblock %}

posts/templates/posts/liked_posts.html
{% extends 'posts/base.html' %}

{% block title %}My Posts - Kragaht{% endblock %}

{% block content %}
<h2>Your Liked Posts</h2>
<div class="post-container">
    {% for post in posts %}
        <div class="post-card">
            <div class="post-image">
                {% if post.photo %}
                    <img src="{{ post.photo.url }}" alt="{{ post.title }}">
                {% else %}
                    <div class="placeholder-image"></div>
                {% endif %}
                <div class="read-post-container">
                    <a href="{% url 'posts:post_detail' post.slug %}" class="read-post">Read Post</a>
                </div>
            </div>
            <div class="post-cont-content">
                <div class="post-header">
                    <div class="post-title">{{ post.title }}</div>
                    <div class="post-meta">
                        <span>Date: {{ post.time_update|date:"d-m-Y H:i" }}</span>
                    </div>
                </div>
                <div class="post-description">
                    {{ post.content|truncatewords:20 }}
                </div>
            </div>
        </div>
    {% empty %}
    <p>You haven't any liked posts yet.</p>
    {% endfor %}
</div>
{% endblock %}

posts/templates/posts/login.html
{% extends 'posts/base.html' %}

{% block title %}Login - Kragaht{% endblock %}

{% block content %}
<div class="register-container">
    <div class="register-box">
        <h2 class="register-title">Login</h2>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                {{ form.username.label_tag }}
                {{ form.username }}
            </div>
            <div class="form-group">
                {{ form.password.label_tag }}
                {{ form.password }}
            </div>
            <button type="submit" class="submit-button">Login</button>
        </form>
    </div>
</div>
{% endblock %}

posts/templates/posts/my_posts.html
{% extends 'posts/base.html' %}

{% block title %}My Posts - Kragaht{% endblock %}

{% block content %}
<h2>Your Posts</h2>
<div class="post-container">
    {% for post in posts %}
        <div class="post-card">
            <div class="post-image">
                {% if post.photo %}
                    <img src="{{ post.photo.url }}" alt="{{ post.title }}">
                {% else %}
                    <div class="placeholder-image"></div>
                {% endif %}
                <div class="read-post-container">
                    <a href="{% url 'posts:post_detail' post.slug %}" class="read-post">Read Post</a>
                </div>
            </div>
            <div class="post-content">
                <div class="post-header">
                    <div class="post-title">{{ post.title }}</div>
                    <div class="post-meta">
                        <span>Date: {{ post.time_update|date:"d-m-Y H:i" }}</span>
                    </div>
                </div>
                <div class="post-description">
                    {{ post.content|truncatewords:20 }}
                </div>
            </div>
        </div>
    {% empty %}
    <p>You haven't published any posts yet.</p>
    {% endfor %}
</div>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'posts/base.html' %}

{% block title %}{{ post.title }} - Kragaht{% endblock %}

{% block content %}
<div class="post-detail-container">
    <div class="main-post">
        <div class="det-post-title">{{ post.title }}</div>
        <p><strong>Category:</strong> {{ post.category }}</p>

        {% if post.photo %}
            <div class="post-image-wrapper">
                <img src="{{ post.photo.url }}" alt="Post Photo">
            </div>
        {% endif %}

        <div class="post-content">
            {{ post.content|safe }}  <!-- Render CKEditor -->
        </div>

        <div>
            {% if user.is_authenticated %}
                <a href="{% url 'posts:post_edit' post.id %}" class="sl">Edit</a>
                <form action="{% url 'posts:post_delete' post.id %}" method="post" style="display: inline;">
                    {% csrf_token %}
                    <input type="submit" value="Delete" class="del-but" onclick="return confirm('Are you sure you want to delete this post?');">
                </form>
                <p>You can only edit or delete your own posts, if post is not yours, you will be redirected</p>
            {% endif %}
        </div>
    </div>

    <aside class="similar-posts">
        <h3>Interesting Posts</h3>
        <ul>
            {% for similar_post in similar_posts %}
                <li><a href="{% url 'posts:post_detail' similar_post.slug %}">{{ similar_post.title }}</a></li>
            {% empty %}
                <li>No similar posts found.</li>
            {% endfor %}
        </ul>
    </aside>
</div>
{% endblock %}

posts/templates/posts/post_form.html
{% extends 'posts/base.html' %}

{% block title %}Create/Edit Post{% endblock %}

{% block content %}
<div class="post-form-container">
    <h2>Create/Edit Post</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}  <!-- Loads CKEditor JavaScript -->
        {{ form.as_p }}

        <button type="submit" class="submit-button">Save</button>
    </form>
</div>
{% endblock %}

posts/templates/posts/post_list.html
{% extends 'posts/base.html' %}

{% block title %}Post List - Kragaht{% endblock %}

{% block content %}
<h2>You need to log in to be able to create/edit or like posts</h2>
<div class="post-container">
    <!-- Sorting Dropdown -->
    <div class="sort-options">
        <form method="get" class="sort-form" action="{% url 'posts:post_list' %}">
            <input type="hidden" name="q" value="{{ query|default:'' }}">

            <label for="sort-select">Sort by:</label>
            <select name="sort" id="sort-select">
                <option value="name" {% if sort_by == 'name' %}selected{% endif %}>Name</option>
                <option value="likes" {% if sort_by == 'likes' %}selected{% endif %}>Likes</option>
                <option value="time_create" {% if sort_by == 'time_create' %}selected{% endif %}>Time of Creation</option>
            </select>

            <button type="submit" class="sort-button">Sort</button>
        </form>
    </div>

    {% for post in posts %}
        <div class="post-card">

            <div class="post-image">
                {% if post.photo %}
                    <img src="{{ post.photo.url }}" alt="{{ post.title }}">
                {% else %}
                    <div class="placeholder-image"></div>
                {% endif %}
                <div class="read-post-container">
                    <a href="{% url 'posts:post_detail' post.slug %}" class="read-post">Read Post</a>

                    <!-- Like System -->
                    <div class="post-interactions">
                        <button class="like-button" data-id="{{ post.id }}">
                            {% if user.is_authenticated and post.user_liked %}
                                &#9650; <!-- Arrow for Liked -->
                            {% else %}
                                &#9650; <!-- Another arrow for dislike -->
                            {% endif %}
                        </button>
                        <span id="like-count-{{ post.id }}">{{ post.get_like_count }}</span>: Likes
                    </div>
                </div>
            </div>

            <!-- Post Content -->
            <div class="post-cont-content">
                <div class="post-header">
                    <div class="post-title">{{ post.title }}</div>
                    <div class="post-meta">
                        <span>Author: {{ post.author.username }}</span>
                        <span>Date: {{ post.time_update|date:"d-m-Y H:i" }}</span>
                    </div>
                </div>
                <div class="post-description">
                    {{ post.content|safe|truncatechars:150 }}
                </div>
            </div>
        </div>
    {% empty %}
    <p>No posts available.</p>
    {% endfor %}
</div>

<!-- JavaScript AJAX Like System -->
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const likeButtons = document.querySelectorAll('.like-button');

        likeButtons.forEach(button => {
            button.addEventListener('click', function () {
                const postId = this.getAttribute('data-id');
                const likeCountSpan = document.getElementById(`like-count-${postId}`);

                fetch(`/post/${postId}/like/`, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': '{{ csrf_token }}',
                    },
                })
                .then(response => {
                    if (!response.ok) {
                        throw new Error('Network response was not ok');
                    }
                    return response.json();
                })
                .then(data => {
                    if (data.liked !== undefined) {
                        this.innerHTML = data.liked ? '&#9650;' : '&#9650;';
                        likeCountSpan.textContent = data.like_count;
                    }
                })
                .catch(error => console.error('Error:', error));
            });
        });
    });
</script>
{% endblock %}

posts/templates/posts/register.html
{% extends 'posts/base.html' %}

{% block title %}Register - Kragaht{% endblock %}

{% block content %}
<div class="register-container">
    <div class="register-box">
        <h2 class="register-title">Sign In</h2>
        <form method="post">
    {% csrf_token %}
    <div class="form-group">
        {{ form.username.label_tag }}
        {{ form.username }}
    </div>
    <div class="form-group">
        {{ form.password1.label_tag }}
        {{ form.password1 }}
    </div>
    <div class="form-group">
        {{ form.password2.label_tag }}
        {{ form.password2 }}
    </div>
    <button type="submit" class="submit-button">Register</button>
</form>
    </div>
</div>
{% endblock %}

posts/templates/posts/show_category.html
{% extends 'posts/base.html' %}

{% block title %}Post List - Kragaht{% endblock %}

{% block content %}
<div class="post-container">
    {% for post in posts %}
        <div class="post-card">
            <div class="post-image">
                {% if post.photo %}
                    <img src="{{ post.photo.url }}" alt="{{ post.title }}">
                {% else %}
                    <div class="placeholder-image"></div>
                {% endif %}
                <div class="read-post-container">
                    <a href="{% url 'posts:post_detail' post.slug %}" class="read-post">Read Post</a>
                    <div class="post-interactions">
                        <div class="arrow upvote" data-action="like" data-id="{{ post.id }}">&#9650;</div>
                        <div class="votes-number" id="votes-count-{{ post.id }}">{{ post.get_votes }}</div>
                        <div class="arrow downvote" data-action="dislike" data-id="{{ post.id }}">&#9660;</div>
                    </div>
                </div>
            </div>
            <div class="post-content">
                <div class="post-header">
                    <div class="post-title">{{ post.title }}</div>
                    <div class="post-meta">
                        <span>Author: {{ post.author.username }}</span>
                        <span>Date: {{ post.time_update|date:"d-m-Y H:i" }}</span>
                    </div>
                </div>
                <div class="post-description">
                    {{ post.content|truncatewords:20 }}
                </div>
            </div>
        </div>
    {% endfor %}
</div>

{% endblock %}